NeuralNetCpp: nn::SGD Class Reference
nn::SGD Class Reference
Stochastic gradient descent with optional momentum and weight decay.
#include <optimizer.hpp>
Public Member Functions
SGD (const std::vector< Tensor * > &parameters, double learning_rate, double momentum=0.0, double weight_decay=0.0)
Constructs SGD optimizer.
void step () override
Applies one SGD update step.
void set_learning_rate (double lr)
Updates learning rate.
double get_learning_rate () const
Returns current learning rate.
Public Member Functions inherited from nn::Optimizer
virtual ~Optimizer ()=default
Virtual destructor for optimizer polymorphism.
void zero_grad ()
Zeros gradients of all managed parameters.
Private Attributes
double learning_rate_
double momentum_
double weight_decay_
std::unordered_map< Tensor *, Tensor > velocities_
Additional Inherited Members
Protected Attributes inherited from nn::Optimizer
std::vector< Tensor * > parameters_
Detailed Description
Stochastic gradient descent with optional momentum and weight decay.
Definition at line 32 of file optimizer.hpp.
Constructor & Destructor Documentation
SGD()
nn::SGD::SGD (const std::vector< Tensor * > & parameters, double learning_rate, double momentum = 0.0, double weight_decay = 0.0)
Constructs SGD optimizer.
Parameters
parameters Parameter tensors to update.
learning_rate Base step size.
momentum Momentum coefficient in [0, 1] for velocity smoothing.
weight_decay L2 regularization coefficient.
Definition at line 29 of file optimizer.cpp.
References learning_rate_, momentum_, nn::Optimizer::parameters_, velocities_, weight_decay_, and nn::Tensor::zeros().
Member Function Documentation
get_learning_rate()
double nn::SGD::get_learning_rate () const inline
Returns current learning rate.
Returns
Learning rate currently used for updates.
Definition at line 57 of file optimizer.hpp.
References learning_rate_.
set_learning_rate()
void nn::SGD::set_learning_rate (double lr) inline
Updates learning rate.
Parameters
lr New learning rate value.
Definition at line 51 of file optimizer.hpp.
References learning_rate_.
step()
void nn::SGD::step () override virtual
Applies one SGD update step.
Implements nn::Optimizer.
Definition at line 46 of file optimizer.cpp.
References nn::Tensor::grad(), learning_rate_, momentum_, nn::Optimizer::parameters_, nn::Tensor::size(), velocities_, weight_decay_, and nn::Tensor::zeros().
Referenced by main().
Member Data Documentation
learning_rate_
double nn::SGD::learning_rate_ private
Definition at line 61 of file optimizer.hpp.
Referenced by get_learning_rate(), set_learning_rate(), SGD(), and step().
momentum_
double nn::SGD::momentum_ private
Definition at line 64 of file optimizer.hpp.
Referenced by SGD(), and step().
velocities_
std::unordered_map<Tensor*, Tensor> nn::SGD::velocities_ private
Definition at line 70 of file optimizer.hpp.
Referenced by SGD(), and step().
weight_decay_
double nn::SGD::weight_decay_ private
Definition at line 67 of file optimizer.hpp.
Referenced by SGD(), and step().
The documentation for this class was generated from the following files:
include/optimizer.hpp
src/optimizer.cpp