NeuralNetCpp: nn::Module Class Reference
nn::Module Class Reference abstract
Module API
Base interface for all trainable or stateless neural-network layers.
#include <module.hpp>
Public Member Functions
virtual ~Module ()=default
Virtual destructor for polymorphic layer hierarchy.
virtual Tensor forward (const Tensor &input)=0
Runs layer forward pass.
virtual std::vector< Tensor * > parameters ()=0
Returns trainable parameters owned by this layer.
void zero_grad ()
Zeros gradients of all parameters returned by parameters().
void train ()
Switches layer behavior to training mode.
void eval ()
Switches layer behavior to evaluation mode.
bool is_training () const
Indicates whether the layer is in training mode.
Protected Attributes
bool training_ = true
Detailed Description
Base interface for all trainable or stateless neural-network layers.
A Module consumes an input tensor in forward(), optionally exposes trainable parameters(), and keeps track of whether the layer should behave in training mode or evaluation mode.
Definition at line 20 of file module.hpp.
Constructor & Destructor Documentation
~Module()
virtual nn::Module::~Module () virtual default
Virtual destructor for polymorphic layer hierarchy.
Member Function Documentation
eval()
void nn::Module::eval () inline
Switches layer behavior to evaluation mode.
Definition at line 45 of file module.hpp.
References training_.
forward()
virtual Tensor nn::Module::forward (const Tensor & input) pure virtual
Runs layer forward pass.
Parameters
input Input tensor.
Returns
Output tensor produced by this layer.
Implemented in nn::Dropout, nn::Linear, nn::ReLU, nn::Sequential, nn::Sigmoid, and nn::Tanh.
is_training()
bool nn::Module::is_training () const inline
Indicates whether the layer is in training mode.
Returns
True when layer behaves in training mode.
Definition at line 51 of file module.hpp.
References training_.
Referenced by nn::Dropout::forward().
parameters()
virtual std::vector< Tensor * > nn::Module::parameters () pure virtual
Returns trainable parameters owned by this layer.
Returns
Vector of non-owning pointers to parameter tensors.
Implemented in nn::Dropout, nn::Linear, nn::ReLU, nn::Sequential, nn::Sigmoid, and nn::Tanh.
Referenced by zero_grad().
train()
void nn::Module::train () inline
Switches layer behavior to training mode.
Definition at line 42 of file module.hpp.
References training_.
zero_grad()
void nn::Module::zero_grad ()
Zeros gradients of all parameters returned by parameters().
Definition at line 17 of file module.cpp.
References parameters().
Member Data Documentation
training_
bool nn::Module::training_ = true protected
Definition at line 55 of file module.hpp.
Referenced by eval(), nn::Sequential::eval(), is_training(), train(), and nn::Sequential::train().
The documentation for this class was generated from the following files:
include/module.hpp
src/module.cpp