NeuralNetCpp: nn::Tensor Class Reference
nn::Tensor Class Reference
Tensor API
Dense n-dimensional tensor with optional gradient storage.
#include <tensor.hpp>
Public Types
using value_type = double
Element type stored in the tensor buffer.
using shape_type = std::vector<size_t>
Shape representation where each entry is one dimension size.
Public Member Functions
Tensor (const shape_type &shape, bool requires_grad=false)
Creates a zero-initialized tensor with the provided shape.
Tensor (const std::vector< value_type > &data, const shape_type &shape, bool requires_grad=false)
Creates a tensor from explicit data and shape.
Tensor (const Tensor &other)
Copy-constructs a tensor.
Tensor (Tensor &&other) noexcept
Move-constructs a tensor.
Tensor & operator= (const Tensor &other)
Copy-assigns a tensor.
Tensor & operator= (Tensor &&other) noexcept
Move-assigns a tensor.
~Tensor ()=default
const shape_type & shape () const
Returns the tensor shape.
size_t ndim () const
Returns the number of dimensions.
size_t size () const
Returns total number of stored elements.
value_type * data ()
Returns mutable pointer to contiguous storage.
const value_type * data () const
Returns read-only pointer to contiguous storage.
bool requires_grad () const
Reports whether gradient tracking is enabled.
void set_requires_grad (bool value)
Enables or disables gradient tracking.
value_type & operator[] (size_t idx)
Returns mutable element access by flat index.
const value_type & operator[] (size_t idx) const
Returns read-only element access by flat index.
value_type & at (const std::vector< size_t > &indices)
Returns mutable access using multi-dimensional coordinates.
const value_type & at (const std::vector< size_t > &indices) const
Returns read-only access using multi-dimensional coordinates.
Tensor operator+ (const Tensor &other) const
Computes element-wise addition.
Tensor operator- (const Tensor &other) const
Computes element-wise subtraction.
Tensor operator* (const Tensor &other) const
Computes element-wise multiplication.
Tensor operator/ (const Tensor &other) const
Computes element-wise division.
Tensor operator+ (value_type scalar) const
Adds scalar to all tensor elements.
Tensor operator- (value_type scalar) const
Subtracts scalar from all tensor elements.
Tensor operator* (value_type scalar) const
Multiplies all tensor elements by scalar.
Tensor operator/ (value_type scalar) const
Divides all tensor elements by scalar.
Tensor & operator+= (const Tensor &other)
Adds another tensor in place.
Tensor & operator-= (const Tensor &other)
Subtracts another tensor in place.
Tensor & operator*= (const Tensor &other)
Multiplies by another tensor in place.
Tensor & operator*= (value_type scalar)
Multiplies by scalar in place.
Tensor matmul (const Tensor &other) const
Performs 2D matrix multiplication.
Tensor transpose () const
Returns matrix transpose for a 2D tensor.
Tensor sum () const
Reduces all elements by summation.
Tensor sum (int axis) const
Reduces elements by summation along one axis.
Tensor mean () const
Computes mean across all elements.
Tensor mean (int axis) const
Computes mean along one axis.
value_type max () const
Returns largest stored value.
value_type min () const
Returns smallest stored value.
Tensor reshape (const shape_type &new_shape) const
Returns tensor data reinterpreted with a new shape.
Tensor flatten () const
Flattens tensor into one dimension.
Tensor slice (size_t start, size_t end, size_t axis=0) const
Returns a slice range along selected axis.
Tensor & grad ()
Returns mutable gradient tensor.
const Tensor & grad () const
Returns read-only gradient tensor.
bool has_grad () const
Indicates whether gradient storage exists.
std::shared_ptr< Tensor > grad_ptr () const
Returns shared pointer to gradient storage.
void ensure_grad ()
Allocates gradient tensor when not already present.
void set_autograd (std::function< void()> backward_fn, std::vector< std::shared_ptr< Tensor > > parents)
Stores local backward callback and parent tensor list.
void backward ()
Starts backpropagation from this tensor.
void zero_grad ()
Resets gradient values to zero when gradient storage exists.
void print () const
Prints compact tensor summary to standard output.
Static Public Member Functions
static Tensor zeros (const shape_type &shape, bool requires_grad=false)
Creates zero-filled tensor.
static Tensor ones (const shape_type &shape, bool requires_grad=false)
Creates one-filled tensor.
static Tensor randn (const shape_type &shape, bool requires_grad=false)
Creates tensor sampled from standard normal distribution.
static Tensor uniform (const shape_type &shape, value_type low=0.0, value_type high=1.0, bool requires_grad=false)
Creates tensor sampled from uniform distribution.
static std::shared_ptr< Tensor > alias (const Tensor &tensor)
Creates shared tensor copy for autograd parent wiring.
Private Member Functions
void backward_impl ()
Executes backward callback and recursively traverses parents.
size_t compute_index (const std::vector< size_t > &indices) const
Converts multi-dimensional coordinates into flat row-major index.
void check_shape_compatible (const Tensor &other) const
Validates shape compatibility for element-wise operations.
void allocate_grad ()
Allocates zero-initialized gradient tensor matching shape().
Private Attributes
std::vector< value_type > data_
shape_type shape_
std::shared_ptr< Tensor > grad_
bool requires_grad_
std::function< void()> backward_fn_
std::vector< std::shared_ptr< Tensor > > parents_
Friends
std::ostream & operator<< (std::ostream &os, const Tensor &t)
Streams compact tensor representation.
Detailed Description
Dense n-dimensional tensor with optional gradient storage.
Tensor owns a flat contiguous buffer and a shape vector describing how that buffer should be interpreted. Most math operations return a new Tensor and, when gradients are enabled, attach lightweight autograd metadata so backward() can propagate gradients to upstream tensors.
Definition at line 24 of file tensor.hpp.
Member Typedef Documentation
shape_type
using nn::Tensor::shape_type = std::vector<size_t>
Shape representation where each entry is one dimension size.
Definition at line 30 of file tensor.hpp.
value_type
using nn::Tensor::value_type = double
Element type stored in the tensor buffer.
Definition at line 27 of file tensor.hpp.
Constructor & Destructor Documentation
Tensor() [1/4]
nn::Tensor::Tensor (const shape_type & shape, bool requires_grad = false) explicit
Creates a zero-initialized tensor with the provided shape.
Parameters
shape Tensor dimensions in row-major order.
requires_grad Whether operations involving this tensor should track gradients.
Exceptions
std::invalid_argument If any dimension in shape is zero.
Definition at line 79 of file tensor.cpp.
References allocate_grad(), data_, grad_, requires_grad(), requires_grad_, shape(), and shape_.
Referenced by alias(), check_shape_compatible(), flatten(), grad(), grad(), matmul(), mean(), mean(), ones(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/(), operator<<, operator=(), operator=(), randn(), reshape(), slice(), sum(), sum(), Tensor(), Tensor(), transpose(), uniform(), and zeros().
Tensor() [2/4]
nn::Tensor::Tensor (const std::vector< value_type > & data, const shape_type & shape, bool requires_grad = false)
Creates a tensor from explicit data and shape.
Parameters
data Flat row-major tensor values.
shape Tensor dimensions used to interpret data.
requires_grad Whether operations involving this tensor should track gradients.
Exceptions
std::invalid_argument If data size does not match shape product.
Definition at line 99 of file tensor.cpp.
References allocate_grad(), data(), data_, grad_, requires_grad(), requires_grad_, shape(), and shape_.
Tensor() [3/4]
nn::Tensor::Tensor (const Tensor & other)
Copy-constructs a tensor.
Parameters
other Source tensor to copy.
Definition at line 122 of file tensor.cpp.
References allocate_grad(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
Tensor() [4/4]
nn::Tensor::Tensor (Tensor && other) noexcept
Move-constructs a tensor.
Parameters
other Source tensor to move.
Definition at line 137 of file tensor.cpp.
References backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
~Tensor()
nn::Tensor::~Tensor () default
Member Function Documentation
alias()
std::shared_ptr< Tensor > nn::Tensor::alias (const Tensor & tensor) static
Creates shared tensor copy for autograd parent wiring.
Parameters
tensor Source tensor to alias.
Returns
Shared pointer holding copied tensor state.
Definition at line 942 of file tensor.cpp.
References Tensor().
Referenced by nn::losses::binary_cross_entropy(), matmul(), mean(), operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), operator/(), nn::activations::relu(), nn::activations::sigmoid(), sum(), sum(), and transpose().
allocate_grad()
void nn::Tensor::allocate_grad () private
Allocates zero-initialized gradient tensor matching shape().
Definition at line 914 of file tensor.cpp.
References grad_, and shape_.
Referenced by backward(), ensure_grad(), operator=(), Tensor(), Tensor(), and Tensor().
at() [1/2]
Tensor::value_type & nn::Tensor::at (const std::vector< size_t > & indices)
Returns mutable access using multi-dimensional coordinates.
Parameters
indices Per-dimension coordinates.
Returns
Mutable reference to indexed element.
Exceptions
std::invalid_argument If index rank does not match tensor rank.
std::out_of_range If any coordinate is outside shape bounds.
Definition at line 180 of file tensor.cpp.
References compute_index(), and data_.
at() [2/2]
const Tensor::value_type & nn::Tensor::at (const std::vector< size_t > & indices) const
Returns read-only access using multi-dimensional coordinates.
Parameters
indices Per-dimension coordinates.
Returns
Const reference to indexed element.
Exceptions
std::invalid_argument If index rank does not match tensor rank.
std::out_of_range If any coordinate is outside shape bounds.
Definition at line 184 of file tensor.cpp.
References compute_index(), and data_.
backward()
void nn::Tensor::backward ()
Starts backpropagation from this tensor.
Exceptions
std::runtime_error If requires_grad() is false.
Definition at line 949 of file tensor.cpp.
References allocate_grad(), backward_impl(), grad_, and requires_grad_.
Referenced by main().
backward_impl()
void nn::Tensor::backward_impl () private
Executes backward callback and recursively traverses parents.
Definition at line 959 of file tensor.cpp.
References backward_fn_, and parents_.
Referenced by backward().
check_shape_compatible()
void nn::Tensor::check_shape_compatible (const Tensor & other) const private
Validates shape compatibility for element-wise operations.
Parameters
other Other tensor participating in operation.
Exceptions
std::invalid_argument If shape() differs from other.shape().
Definition at line 980 of file tensor.cpp.
References shape_, and Tensor().
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), and operator/().
compute_index()
size_t nn::Tensor::compute_index (const std::vector< size_t > & indices) const private
Converts multi-dimensional coordinates into flat row-major index.
Parameters
indices Per-dimension indices.
Returns
Flat buffer index.
Definition at line 188 of file tensor.cpp.
References shape_.
Referenced by at(), and at().
data() [1/2]
value_type * nn::Tensor::data () inline
Returns mutable pointer to contiguous storage.
Returns
Mutable raw pointer to element data.
Definition at line 122 of file tensor.hpp.
References data_.
Referenced by Tensor().
data() [2/2]
const value_type * nn::Tensor::data () const inline
Returns read-only pointer to contiguous storage.
Returns
Const raw pointer to element data.
Definition at line 128 of file tensor.hpp.
References data_.
ensure_grad()
void nn::Tensor::ensure_grad ()
Allocates gradient tensor when not already present.
Definition at line 928 of file tensor.cpp.
References allocate_grad(), and grad_.
flatten()
Tensor nn::Tensor::flatten () const
Flattens tensor into one dimension.
Returns
Tensor with shape {size()}.
Definition at line 835 of file tensor.cpp.
References data_, reshape(), and Tensor().
grad() [1/2]
Tensor & nn::Tensor::grad () inline
Returns mutable gradient tensor.
Returns
Mutable gradient tensor reference.
Definition at line 389 of file tensor.hpp.
References grad_, and Tensor().
Referenced by main(), nn::Adam::step(), and nn::SGD::step().
grad() [2/2]
const Tensor & nn::Tensor::grad () const inline
Returns read-only gradient tensor.
Returns
Const gradient tensor reference.
Definition at line 395 of file tensor.hpp.
References grad_, and Tensor().
grad_ptr()
std::shared_ptr< Tensor > nn::Tensor::grad_ptr () const inline
Returns shared pointer to gradient storage.
Returns
Shared gradient tensor pointer.
Definition at line 407 of file tensor.hpp.
References grad_.
Referenced by nn::losses::binary_cross_entropy(), nn::activations::relu(), and nn::activations::sigmoid().
has_grad()
bool nn::Tensor::has_grad () const inline
Indicates whether gradient storage exists.
Returns
True when gradient tensor has been allocated.
Definition at line 401 of file tensor.hpp.
References grad_.
matmul()
Tensor nn::Tensor::matmul (const Tensor & other) const
Performs 2D matrix multiplication.
Parameters
other Right-hand matrix.
Returns
Matrix product tensor.
Exceptions
std::invalid_argument If either tensor is not 2D or dimensions are incompatible.
Definition at line 539 of file tensor.cpp.
References alias(), data_, requires_grad_, shape_, sum(), and Tensor().
Referenced by nn::Linear::forward(), and main().
max()
Tensor::value_type nn::Tensor::max () const
Returns largest stored value.
Returns
Maximum element value.
Definition at line 813 of file tensor.cpp.
References data_.
mean() [1/2]
Tensor nn::Tensor::mean () const
Computes mean across all elements.
Returns
Rank-1 tensor of shape {1} containing global mean.
Definition at line 763 of file tensor.cpp.
References alias(), data_, requires_grad_, and Tensor().
Referenced by nn::losses::mae_loss(), and nn::losses::mse_loss().
mean() [2/2]
Tensor nn::Tensor::mean (int axis) const
Computes mean along one axis.
Parameters
axis Reduction axis. Negative values are normalized from the end.
Returns
Tensor with axis removed and averaged values.
Exceptions
std::invalid_argument If reducing axis on empty shape.
std::out_of_range If axis is invalid.
Definition at line 793 of file tensor.cpp.
References shape_, sum(), and Tensor().
min()
Tensor::value_type nn::Tensor::min () const
Returns smallest stored value.
Returns
Minimum element value.
Definition at line 817 of file tensor.cpp.
References data_.
ndim()
size_t nn::Tensor::ndim () const inline
Returns the number of dimensions.
Returns
Rank of the tensor.
Definition at line 110 of file tensor.hpp.
References shape_.
ones()
Tensor nn::Tensor::ones (const shape_type & shape, bool requires_grad = false) static
Creates one-filled tensor.
Parameters
shape Tensor dimensions.
requires_grad Whether returned tensor should track gradients.
Returns
One-initialized tensor.
Definition at line 874 of file tensor.cpp.
References data_, requires_grad(), shape(), and Tensor().
Referenced by main().
operator*() [1/2]
Tensor nn::Tensor::operator* (const Tensor & other) const
Computes element-wise multiplication.
Parameters
other Tensor multiplied element-wise.
Returns
Product tensor with same shape as operands.
Exceptions
std::invalid_argument If tensor shapes are not equal.
Definition at line 293 of file tensor.cpp.
References alias(), backward_fn_, check_shape_compatible(), data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator*() [2/2]
Tensor nn::Tensor::operator* (value_type scalar) const
Multiplies all tensor elements by scalar.
Parameters
scalar Scalar multiplier.
Returns
Tensor with scaled values.
Definition at line 437 of file tensor.cpp.
References alias(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator*=() [1/2]
Tensor & nn::Tensor::operator*= (const Tensor & other)
Multiplies by another tensor in place.
Parameters
other Tensor multiplied element-wise.
Returns
Reference to this tensor.
Exceptions
std::invalid_argument If tensor shapes are not equal.
Definition at line 519 of file tensor.cpp.
References check_shape_compatible(), data_, and Tensor().
operator*=() [2/2]
Tensor & nn::Tensor::operator*= (value_type scalar)
Multiplies by scalar in place.
Parameters
scalar Scalar multiplier.
Returns
Reference to this tensor.
Definition at line 529 of file tensor.cpp.
References data_, and Tensor().
operator+() [1/2]
Tensor nn::Tensor::operator+ (const Tensor & other) const
Computes element-wise addition.
Parameters
other Tensor added element-wise.
Returns
Sum tensor with same shape as operands.
Exceptions
std::invalid_argument If tensor shapes are not equal.
Definition at line 210 of file tensor.cpp.
References alias(), backward_fn_, check_shape_compatible(), data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator+() [2/2]
Tensor nn::Tensor::operator+ (value_type scalar) const
Adds scalar to all tensor elements.
Parameters
scalar Scalar value to add.
Returns
Tensor with scalar-added values.
Definition at line 380 of file tensor.cpp.
References alias(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator+=()
Tensor & nn::Tensor::operator+= (const Tensor & other)
Adds another tensor in place.
Parameters
other Tensor added element-wise.
Returns
Reference to this tensor.
Exceptions
std::invalid_argument If tensor shapes are not equal.
Definition at line 497 of file tensor.cpp.
References check_shape_compatible(), data_, and Tensor().
operator-() [1/2]
Tensor nn::Tensor::operator- (const Tensor & other) const
Computes element-wise subtraction.
Parameters
other Tensor subtracted element-wise.
Returns
Difference tensor with same shape as operands.
Exceptions
std::invalid_argument If tensor shapes are not equal.
Definition at line 252 of file tensor.cpp.
References alias(), backward_fn_, check_shape_compatible(), data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator-() [2/2]
Tensor nn::Tensor::operator- (value_type scalar) const
Subtracts scalar from all tensor elements.
Parameters
scalar Scalar value to subtract.
Returns
Tensor with scalar-subtracted values.
Definition at line 409 of file tensor.cpp.
References alias(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator-=()
Tensor & nn::Tensor::operator-= (const Tensor & other)
Subtracts another tensor in place.
Parameters
other Tensor subtracted element-wise.
Returns
Reference to this tensor.
Exceptions
std::invalid_argument If tensor shapes are not equal.
Definition at line 509 of file tensor.cpp.
References check_shape_compatible(), data_, and Tensor().
operator/() [1/2]
Tensor nn::Tensor::operator/ (const Tensor & other) const
Computes element-wise division.
Parameters
other Tensor used as element-wise divisor.
Returns
Quotient tensor with same shape as operands.
Exceptions
std::invalid_argument If tensor shapes are not equal.
std::runtime_error If any divisor element is zero.
Definition at line 334 of file tensor.cpp.
References alias(), backward_fn_, check_shape_compatible(), data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator/() [2/2]
Tensor nn::Tensor::operator/ (value_type scalar) const
Divides all tensor elements by scalar.
Parameters
scalar Scalar divisor.
Returns
Tensor with scaled values.
Exceptions
std::runtime_error If scalar is zero.
Definition at line 465 of file tensor.cpp.
References alias(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator=() [1/2]
Tensor & nn::Tensor::operator= (const Tensor & other)
Copy-assigns a tensor.
Parameters
other Source tensor to copy.
Returns
Reference to this tensor.
Definition at line 145 of file tensor.cpp.
References allocate_grad(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator=() [2/2]
Tensor & nn::Tensor::operator= (Tensor && other) noexcept
Move-assigns a tensor.
Parameters
other Source tensor to move.
Returns
Reference to this tensor.
Definition at line 160 of file tensor.cpp.
References backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
operator[]() [1/2]
value_type & nn::Tensor::operator[] (size_t idx) inline
Returns mutable element access by flat index.
Parameters
idx Zero-based flat index.
Returns
Mutable reference to element at idx.
Definition at line 147 of file tensor.hpp.
References data_.
operator[]() [2/2]
const value_type & nn::Tensor::operator[] (size_t idx) const inline
Returns read-only element access by flat index.
Parameters
idx Zero-based flat index.
Returns
Const reference to element at idx.
Definition at line 154 of file tensor.hpp.
References data_.
print()
void nn::Tensor::print () const
Prints compact tensor summary to standard output.
Definition at line 986 of file tensor.cpp.
randn()
Tensor nn::Tensor::randn (const shape_type & shape, bool requires_grad = false) static
Creates tensor sampled from standard normal distribution.
Parameters
shape Tensor dimensions.
requires_grad Whether returned tensor should track gradients.
Returns
Random tensor sampled from N(0,1).
Definition at line 881 of file tensor.cpp.
References data_, requires_grad(), shape(), and Tensor().
Referenced by nn::Linear::initialize_parameters().
requires_grad()
bool nn::Tensor::requires_grad () const inline
Reports whether gradient tracking is enabled.
Returns
True when this tensor participates in autograd.
Definition at line 134 of file tensor.hpp.
References requires_grad_.
Referenced by nn::losses::binary_cross_entropy(), nn::losses::cross_entropy_loss(), nn::activations::elu(), nn::Dropout::forward(), nn::activations::leaky_relu(), nn::losses::mae_loss(), ones(), randn(), nn::activations::relu(), nn::activations::sigmoid(), nn::activations::softmax(), nn::activations::tanh(), Tensor(), Tensor(), uniform(), and zeros().
reshape()
Tensor nn::Tensor::reshape (const shape_type & new_shape) const
Returns tensor data reinterpreted with a new shape.
Parameters
new_shape Requested output shape.
Returns
Tensor containing same element order with new shape.
Exceptions
std::invalid_argument If new_shape product differs from size().
Definition at line 823 of file tensor.cpp.
References data_, requires_grad_, and Tensor().
Referenced by flatten().
set_autograd()
void nn::Tensor::set_autograd (std::function< void()> backward_fn, std::vector< std::shared_ptr< Tensor > > parents)
Stores local backward callback and parent tensor list.
Parameters
backward_fn Callback implementing local derivative propagation.
parents Upstream tensors used during graph traversal.
Definition at line 934 of file tensor.cpp.
References backward_fn_, and parents_.
Referenced by nn::losses::binary_cross_entropy(), nn::activations::relu(), and nn::activations::sigmoid().
set_requires_grad()
void nn::Tensor::set_requires_grad (bool value) inline
Enables or disables gradient tracking.
Parameters
value True to enable autograd recording, false to disable.
Definition at line 140 of file tensor.hpp.
References requires_grad_.
shape()
const shape_type & nn::Tensor::shape () const inline
Returns the tensor shape.
Returns
Shape vector describing tensor dimensions.
Definition at line 104 of file tensor.hpp.
References shape_.
Referenced by nn::losses::binary_cross_entropy(), nn::losses::cross_entropy_loss(), nn::activations::elu(), nn::Dropout::forward(), nn::Linear::forward(), nn::activations::leaky_relu(), nn::losses::mae_loss(), nn::losses::mse_loss(), ones(), randn(), nn::activations::relu(), nn::activations::sigmoid(), nn::activations::softmax(), nn::activations::tanh(), Tensor(), Tensor(), uniform(), and zeros().
size()
size_t nn::Tensor::size () const
Returns total number of stored elements.
Returns
Element count in the flat storage buffer.
Definition at line 174 of file tensor.cpp.
References data_.
Referenced by nn::losses::binary_cross_entropy(), nn::activations::elu(), nn::Dropout::forward(), nn::activations::leaky_relu(), nn::losses::mae_loss(), main(), nn::activations::relu(), nn::activations::sigmoid(), nn::SGD::step(), and nn::activations::tanh().
slice()
Tensor nn::Tensor::slice (size_t start, size_t end, size_t axis = 0) const
Returns a slice range along selected axis.
Parameters
start Inclusive start index on axis.
end Exclusive end index on axis.
axis Axis to slice, currently only axis 0 is supported.
Returns
Sliced tensor containing copied values.
Exceptions
std::out_of_range If axis is invalid.
std::invalid_argument If start/end range is invalid.
std::runtime_error If axis other than 0 is requested.
Definition at line 839 of file tensor.cpp.
References data_, requires_grad_, shape_, and Tensor().
sum() [1/2]
Tensor nn::Tensor::sum () const
Reduces all elements by summation.
Returns
Rank-1 tensor of shape {1} containing total sum.
Definition at line 665 of file tensor.cpp.
References alias(), data_, requires_grad_, and Tensor().
Referenced by matmul(), and mean().
sum() [2/2]
Tensor nn::Tensor::sum (int axis) const
Reduces elements by summation along one axis.
Parameters
axis Reduction axis. Negative values are normalized from the end.
Returns
Tensor with axis removed and remaining dimensions preserved.
Exceptions
std::invalid_argument If reducing axis on empty shape.
std::out_of_range If axis is invalid.
Definition at line 692 of file tensor.cpp.
References alias(), backward_fn_, data_, grad_, parents_, requires_grad_, shape_, and Tensor().
transpose()
Tensor nn::Tensor::transpose () const
Returns matrix transpose for a 2D tensor.
Returns
Transposed 2D tensor.
Exceptions
std::invalid_argument If tensor is not 2D.
Definition at line 623 of file tensor.cpp.
References alias(), data_, requires_grad_, shape_, and Tensor().
uniform()
Tensor nn::Tensor::uniform (const shape_type & shape, value_type low = 0.0, value_type high = 1.0, bool requires_grad = false) static
Creates tensor sampled from uniform distribution.
Parameters
shape Tensor dimensions.
low Lower sampling bound.
high Upper sampling bound.
requires_grad Whether returned tensor should track gradients.
Returns
Random tensor sampled from uniform distribution.
Definition at line 896 of file tensor.cpp.
References data_, requires_grad(), shape(), and Tensor().
zero_grad()
void nn::Tensor::zero_grad ()
Resets gradient values to zero when gradient storage exists.
Definition at line 921 of file tensor.cpp.
References grad_.
zeros()
Tensor nn::Tensor::zeros (const shape_type & shape, bool requires_grad = false) static
Creates zero-filled tensor.
Parameters
shape Tensor dimensions.
requires_grad Whether returned tensor should track gradients.
Returns
Zero-initialized tensor.
Definition at line 869 of file tensor.cpp.
References requires_grad(), shape(), and Tensor().
Referenced by nn::Adam::Adam(), nn::Linear::initialize_parameters(), nn::SGD::SGD(), nn::Adam::step(), and nn::SGD::step().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Tensor & t) friend
Streams compact tensor representation.
Parameters
os Output stream.
t Tensor to serialize.
Returns
Reference to output stream.
Definition at line 990 of file tensor.cpp.
References data_, shape_, and Tensor().
Member Data Documentation
backward_fn_
std::function<void()> nn::Tensor::backward_fn_ private
Definition at line 46 of file tensor.hpp.
Referenced by backward_impl(), operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), operator/(), operator=(), operator=(), set_autograd(), sum(), Tensor(), and Tensor().
data_
std::vector<value_type> nn::Tensor::data_ private
Definition at line 34 of file tensor.hpp.
Referenced by at(), at(), data(), data(), flatten(), matmul(), max(), mean(), min(), ones(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/(), operator<<, operator=(), operator=(), operator[](), operator[](), randn(), reshape(), size(), slice(), sum(), sum(), Tensor(), Tensor(), Tensor(), Tensor(), transpose(), and uniform().
grad_
std::shared_ptr<Tensor> nn::Tensor::grad_ private
Definition at line 40 of file tensor.hpp.
Referenced by allocate_grad(), backward(), ensure_grad(), grad(), grad(), grad_ptr(), has_grad(), operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), operator/(), operator=(), operator=(), sum(), Tensor(), Tensor(), Tensor(), Tensor(), and zero_grad().
parents_
std::vector<std::shared_ptr<Tensor> > nn::Tensor::parents_ private
Definition at line 49 of file tensor.hpp.
Referenced by backward_impl(), operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), operator/(), operator=(), operator=(), set_autograd(), sum(), Tensor(), and Tensor().
requires_grad_
bool nn::Tensor::requires_grad_ private
Definition at line 43 of file tensor.hpp.
Referenced by backward(), matmul(), mean(), operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), operator/(), operator=(), operator=(), requires_grad(), reshape(), set_requires_grad(), slice(), sum(), sum(), Tensor(), Tensor(), Tensor(), Tensor(), and transpose().
shape_
shape_type nn::Tensor::shape_ private
Definition at line 37 of file tensor.hpp.
Referenced by allocate_grad(), check_shape_compatible(), compute_index(), matmul(), mean(), ndim(), operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), operator/(), operator<<, operator=(), operator=(), shape(), slice(), sum(), Tensor(), Tensor(), Tensor(), Tensor(), and transpose().
The documentation for this class was generated from the following files:
include/tensor.hpp
src/tensor.cpp