NeuralNetCpp: nn::Dropout Class Reference
nn::Dropout Class Reference
Regularization layer that randomly zeroes activations during training.
#include <module.hpp>
Public Member Functions
Dropout (double p=0.5)
Constructs dropout layer.
Tensor forward (const Tensor &input) override
Applies inverted dropout in training mode.
std::vector< Tensor * > parameters () override
Dropout has no trainable parameters.
Public Member Functions inherited from nn::Module
virtual ~Module ()=default
Virtual destructor for polymorphic layer hierarchy.
void zero_grad ()
Zeros gradients of all parameters returned by parameters().
void train ()
Switches layer behavior to training mode.
void eval ()
Switches layer behavior to evaluation mode.
bool is_training () const
Indicates whether the layer is in training mode.
Private Attributes
double p_
Additional Inherited Members
Protected Attributes inherited from nn::Module
bool training_ = true
Detailed Description
Regularization layer that randomly zeroes activations during training.
Definition at line 178 of file module.hpp.
Constructor & Destructor Documentation
Dropout()
nn::Dropout::Dropout (double p = 0.5) explicit
Constructs dropout layer.
Parameters
p Probability of masking each activation.
Exceptions
std::invalid_argument If p is outside range [0, 1].
Definition at line 109 of file module.cpp.
References p_.
Member Function Documentation
forward()
Tensor nn::Dropout::forward (const Tensor & input) override virtual
Applies inverted dropout in training mode.
Parameters
input Input tensor.
Returns
Input-like tensor with randomly masked elements in training mode.
Implements nn::Module.
Definition at line 115 of file module.cpp.
References nn::Module::is_training(), p_, nn::Tensor::requires_grad(), nn::Tensor::shape(), and nn::Tensor::size().
parameters()
std::vector< Tensor * > nn::Dropout::parameters () inline override virtual
Dropout has no trainable parameters.
Implements nn::Module.
Definition at line 195 of file module.hpp.
Member Data Documentation
p_
double nn::Dropout::p_ private
Definition at line 199 of file module.hpp.
Referenced by Dropout(), and forward().
The documentation for this class was generated from the following files:
include/module.hpp
src/module.cpp