NeuralNetCpp: Activation API
Activation API
Stateless nonlinear activation helper functions.
Namespaces
namespace nn::activations
Stateless activation helpers used by module wrappers and direct tensor code.
Functions
Tensor nn::activations::relu (const Tensor &input)
Applies ReLU activation, f(x) = max(0, x).
Tensor nn::activations::sigmoid (const Tensor &input)
Applies sigmoid activation, f(x) = 1 / (1 + exp(-x)).
Tensor nn::activations::tanh (const Tensor &input)
Applies hyperbolic tangent activation.
Tensor nn::activations::softmax (const Tensor &input, int axis=-1)
Applies numerically stable softmax normalization.
Tensor nn::activations::leaky_relu (const Tensor &input, double alpha=0.01)
Applies leaky ReLU activation.
Tensor nn::activations::elu (const Tensor &input, double alpha=1.0)
Applies ELU activation.
Detailed Description
Stateless nonlinear activation helper functions.
Prefer these helpers for pure tensor transformations and custom module implementations where a standalone nonlinearity is required.
Function Documentation
elu()
Tensor nn::activations::elu (const Tensor & input, double alpha = 1.0)
Applies ELU activation.
Parameters
input Input tensor.
alpha ELU scaling coefficient for negative branch.
Returns
Tensor with ELU applied element-wise.
Definition at line 145 of file activations.cpp.
References nn::Tensor::requires_grad(), nn::Tensor::shape(), and nn::Tensor::size().
leaky_relu()
Tensor nn::activations::leaky_relu (const Tensor & input, double alpha = 0.01)
Applies leaky ReLU activation.
Parameters
input Input tensor.
alpha Negative-slope coefficient.
Returns
Tensor with leaky ReLU applied element-wise.
Definition at line 134 of file activations.cpp.
References nn::Tensor::requires_grad(), nn::Tensor::shape(), and nn::Tensor::size().
relu()
Tensor nn::activations::relu (const Tensor & input)
Applies ReLU activation, f(x) = max(0, x).
Parameters
input Input tensor.
Returns
Tensor with ReLU applied element-wise.
Definition at line 17 of file activations.cpp.
References nn::Tensor::alias(), nn::Tensor::grad_ptr(), nn::Tensor::requires_grad(), nn::Tensor::set_autograd(), nn::Tensor::shape(), and nn::Tensor::size().
Referenced by nn::ReLU::forward(), and main().
sigmoid()
Tensor nn::activations::sigmoid (const Tensor & input)
Applies sigmoid activation, f(x) = 1 / (1 + exp(-x)).
Parameters
input Input tensor.
Returns
Tensor with sigmoid applied element-wise.
Definition at line 52 of file activations.cpp.
References nn::Tensor::alias(), nn::Tensor::grad_ptr(), nn::Tensor::requires_grad(), nn::Tensor::set_autograd(), nn::Tensor::shape(), and nn::Tensor::size().
Referenced by nn::Sigmoid::forward(), and main().
softmax()
Tensor nn::activations::softmax (const Tensor & input, int axis = -1)
Applies numerically stable softmax normalization.
Parameters
input Input tensor, currently expected to be 2D.
axis Axis to normalize along, currently row-wise behavior is implemented.
Returns
Tensor containing normalized probabilities.
Exceptions
std::invalid_argument If input is not 2D.
Definition at line 96 of file activations.cpp.
References nn::Tensor::requires_grad(), and nn::Tensor::shape().
Referenced by nn::losses::cross_entropy_loss().
tanh()
Tensor nn::activations::tanh (const Tensor & input)
Applies hyperbolic tangent activation.
Parameters
input Input tensor.
Returns
Tensor with tanh applied element-wise.
Definition at line 85 of file activations.cpp.
References nn::Tensor::requires_grad(), nn::Tensor::shape(), and nn::Tensor::size().
Referenced by nn::Tanh::forward(), and main().