NeuralNetCpp: Loss API
Loss API
Supervised-learning loss functions.
Functions
Tensor nn::losses::mse_loss (const Tensor &predictions, const Tensor &targets)
Computes mean squared error.
Tensor nn::losses::binary_cross_entropy (const Tensor &predictions, const Tensor &targets)
Computes binary cross-entropy loss.
Tensor nn::losses::cross_entropy_loss (const Tensor &logits, const Tensor &targets)
Computes multiclass cross-entropy from logits and targets.
Tensor nn::losses::mae_loss (const Tensor &predictions, const Tensor &targets)
Computes mean absolute error.
Detailed Description
Supervised-learning loss functions.
This group contains objective functions used during optimization. Each function validates shape assumptions and returns a scalar tensor loss.
See the Loss Function Guide for a usage walkthrough.
Loss Function Guide
Overview
Loss functions live in the nn::losses namespace and each returns a scalar Tensor of shape {1}. The returned tensor is part of the autograd graph, so calling backward() on it propagates gradients all the way back through the model.
Choosing the Right Loss
Task Recommended Loss Header function
Regression (continuous output) mse_loss or mae_loss losses.hpp
Binary classification binary_cross_entropy losses.hpp
Multiclass classification cross_entropy_loss losses.hpp
Mean Squared Error (Regression)
Use mse_loss when the output is a continuous value and large errors should be penalised more heavily than small ones:
#include "losses.hpp"
using namespace nn;
Tensor pred = model->forward(x);                    // shape {batch, 1}
Tensor loss = losses::mse_loss(pred, targets);      // scalar {1}
loss.backward();
mae_loss is a less sensitive alternative — it penalises all errors equally and is more robust to outliers:
Tensor loss = losses::mae_loss(pred, targets);
Binary Cross-Entropy (Binary Classification)
Use binary_cross_entropy when the final layer produces a sigmoid probability in (0, 1) and the target is 0 or 1:
// Model output must already be in (0,1) — use Sigmoid as the final layer
auto model = std::make_shared<Sequential>();
model->add(std::make_shared<Linear>(2, 4));
model->add(std::make_shared<ReLU>());
model->add(std::make_shared<Linear>(4, 1));
model->add(std::make_shared<Sigmoid>());
Tensor pred = model->forward(x);                       // in (0,1)
Tensor loss = losses::binary_cross_entropy(pred, y);   // scalar {1}
loss.backward();
Cross-Entropy (Multiclass Classification)
Use cross_entropy_loss when the model produces one logit per class. The function applies softmax internally, so the final layer should be a plain linear layer without an additional softmax activation:
// 3-class problem
auto model = std::make_shared<Sequential>();
model->add(std::make_shared<Linear>(4, 8));
model->add(std::make_shared<ReLU>());
model->add(std::make_shared<Linear>(8, 3));  // raw logits — no softmax here
Tensor logits = model->forward(x);              // shape {batch, 3}
Tensor targets = ...;                           // one-hot, shape {batch, 3}
Tensor loss = losses::cross_entropy_loss(logits, targets);
loss.backward();
Full Training Loop Pattern
for (int epoch = 0; epoch < 100; ++epoch) {
    optimizer.zero_grad();                       // clear previous gradients
    Tensor pred = model->forward(input);
    Tensor loss = losses::mse_loss(pred, target);
    loss.backward();                             // compute gradients
    optimizer.step();                            // update parameters
    if (epoch % 10 == 0) {
        std::cout << "Epoch " << epoch
                  << "  loss=" << loss[0] << "\n";
    }
}
Common Pitfalls
Applying softmax before cross_entropy_loss — cross_entropy_loss includes its own softmax. Adding an explicit softmax layer doubles the normalisation and produces incorrect gradients.
Shape mismatch — all loss functions throw std::invalid_argument when predictions.shape() does not equal targets.shape(). Verify batching.
Calling backward() on a non-scalar — loss functions guarantee a scalar output of shape {1}, so backward() is safe. If you compute a custom reduction and it is not scalar, the call will throw.
Not calling zero_grad() before each step — gradients accumulate additively. Missing a zero_grad() call causes gradient explosion in subsequent epochs.
Function Documentation
binary_cross_entropy()
Tensor nn::losses::binary_cross_entropy (const Tensor & predictions, const Tensor & targets)
Computes binary cross-entropy loss.
Parameters
predictions Predicted probabilities.
targets Binary ground-truth values.
Returns
Scalar tensor of shape {1} containing BCE value.
Exceptions
std::invalid_argument If predictions and targets shapes differ.
Definition at line 29 of file losses.cpp.
References nn::Tensor::alias(), nn::Tensor::grad_ptr(), nn::Tensor::requires_grad(), nn::Tensor::set_autograd(), nn::Tensor::shape(), and nn::Tensor::size().
Referenced by main().
cross_entropy_loss()
Tensor nn::losses::cross_entropy_loss (const Tensor & logits, const Tensor & targets)
Computes multiclass cross-entropy from logits and targets.
Parameters
logits Model logits, typically shape (batch_size, num_classes).
targets One-hot or class-probability targets with same batch and class dimensions.
Returns
Scalar tensor of shape {1} containing average cross-entropy.
Exceptions
std::invalid_argument If logits/targets ranks or batch dimensions are invalid.
Definition at line 74 of file losses.cpp.
References nn::Tensor::requires_grad(), nn::Tensor::shape(), and nn::activations::softmax().
mae_loss()
Tensor nn::losses::mae_loss (const Tensor & predictions, const Tensor & targets)
Computes mean absolute error.
Parameters
predictions Model predictions.
targets Ground-truth values.
Returns
Scalar tensor of shape {1} containing MAE value.
Exceptions
std::invalid_argument If predictions and targets shapes differ.
Definition at line 108 of file losses.cpp.
References nn::Tensor::mean(), nn::Tensor::requires_grad(), nn::Tensor::shape(), and nn::Tensor::size().
mse_loss()
Tensor nn::losses::mse_loss (const Tensor & predictions, const Tensor & targets)
Computes mean squared error.
Parameters
predictions Model predictions.
targets Ground-truth values.
Returns
Scalar tensor of shape {1} containing MSE value.
Exceptions
std::invalid_argument If predictions and targets shapes differ.
Definition at line 17 of file losses.cpp.
References nn::Tensor::mean(), and nn::Tensor::shape().
Referenced by main().