NeuralNetCpp: examples/regression_example.cpp File Reference
regression_example.cpp File Reference
#include <iostream>
#include <vector>
#include <memory>
#include <cmath>
#include "tensor.hpp"
#include "module.hpp"
#include "sequential.hpp"
#include "optimizer.hpp"
#include "losses.hpp"
Functions
void generate_regression_data (std::vector< Tensor > &inputs, std::vector< Tensor > &targets, int num_samples=100)
int main ()
Function Documentation
generate_regression_data()
void generate_regression_data (std::vector< Tensor > & inputs, std::vector< Tensor > & targets, int num_samples = 100)
Definition at line 22 of file regression_example.cpp.
Referenced by main().
main()
int main ()
Definition at line 35 of file regression_example.cpp.
References generate_regression_data(), nn::losses::mse_loss(), nn::SGD::step(), and nn::Optimizer::zero_grad().